[Cache]
enabled               = true
[Finders]
default_finder        = desktop
desktop_launch_prefix =
desktop_icons         = true
desktop_prefix        =
math_prefix           =
unicode_prefix        = .
[General]
grab_focus            = true
[UI]
window_size           = 600 260
