wallpaper {
    monitor = DP-3
    path = /home/oshico/Projects/hyproshico/backgrounds/forest.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-3
    path = /home/oshico/Projects/hyproshico/backgrounds/forest.jpg
    fit_mode = cover
}
