cache{
  enabled               = true
}

finders{
  default_finder        = desktop
  desktop_launch_prefix =
  desktop_icons         = true
  desktop_prefix        =
  math_prefix           =
  unicode_prefix        = .
}

general{
  grab_focus            = true
}

ui{
  window_size           = 600 260
}
