background       = rgb(17, 17, 27)
base             = rgb(30, 30, 46)
text             = rgb(205, 214, 244)
alternate_base   = rgb(49, 50, 68)
bright_text      = rgb(250, 179, 135)
accent           = rgb(203, 166, 247)
accent_secondary = rgb(148, 226, 213)
h1_size          = 20
h2_size          = 16
h3_size          = 14
font_size        = 12
small_font_size  = 10
font_family      = FiraCode Nerd Font Mono
font_family_monospace = FiraCode Nerd Font Mono
rounding_large   = 10
rounding_small   = 6
icon_theme       = Papirus-Dark
